/**
 * Vercel Elysia entry (detected as `app.ts`). Runs on Bun via `bunVersion`.
 * Handler is the Bun bundle from `main.ts`.
 */
import { createRequire } from "node:module";
import "elysia";

// Force Vercel file tracing to include Prisma engines beside the Bun bundle.
const require = createRequire(import.meta.url);
void require.resolve("./dist/vercel/libquery_engine-rhel-openssl-3.0.x.so.node");
void require.resolve("./dist/vercel/libquery_engine-debian-openssl-3.0.x.so.node");

// @ts-expect-error generated by `bun run build:vercel`
export { default } from "./dist/vercel/app.js";
