import type { CalendarEvent, Calendar } from "@workspace/ui/components/calendar/types";
import type { RecurrenceRule } from "@/lib/types/calendar";
import type { EventNotification } from "@workspace/ui/components/calendar/notification-manager";
import type { UserSettings } from "@/lib/types/calendar";
interface UseEventFormProps {
    calendars: Calendar[];
    localSettings: UserSettings;
    onEventSaved?: () => void;
    onClose: () => void;
}
interface UseEventFormReturn {
    selectedEvent: CalendarEvent | null;
    eventViewMode: 'view' | 'edit';
    eventTitle: string;
    eventDescription: string;
    eventStartDate: Date;
    eventEndDate: Date;
    eventStartTime: string;
    eventEndTime: string;
    eventAllDay: boolean;
    eventLocation: string;
    eventCalendarId: string;
    eventReminder: number | null;
    eventNotifications: EventNotification[];
    isRecurring: boolean;
    recurrenceRule: RecurrenceRule | null;
    eventSaving: boolean;
    showRecurringDeleteModal: boolean;
    startDateOpen: boolean;
    endDateOpen: boolean;
    startTimeOpen: boolean;
    endTimeOpen: boolean;
    timeErrors: {
        start?: string;
        end?: string;
    };
    notificationsLoading: boolean;
    showNotifications: boolean;
    setSelectedEvent: (event: CalendarEvent | null) => void;
    setEventViewMode: (mode: 'view' | 'edit') => void;
    setEventTitle: (title: string) => void;
    setEventDescription: (description: string) => void;
    setEventStartDate: (date: Date) => void;
    setEventEndDate: (date: Date) => void;
    setEventStartTime: (time: string) => void;
    setEventEndTime: (time: string) => void;
    setEventAllDay: (allDay: boolean) => void;
    setEventLocation: (location: string) => void;
    setEventCalendarId: (id: string) => void;
    setEventReminder: (reminder: number | null) => void;
    setEventNotifications: (notifications: EventNotification[]) => void;
    setIsRecurring: (recurring: boolean) => void;
    setRecurrenceRule: (rule: RecurrenceRule | null) => void;
    setShowRecurringDeleteModal: (show: boolean) => void;
    setStartDateOpen: (open: boolean) => void;
    setEndDateOpen: (open: boolean) => void;
    setStartTimeOpen: (open: boolean) => void;
    setEndTimeOpen: (open: boolean) => void;
    setShowNotifications: (show: boolean) => void;
    handleStartTimeChange: (newStartTime: string) => void;
    handleEndTimeChange: (newEndTime: string) => void;
    handleNotificationChange: (notifications: EventNotification[]) => void;
    loadEventData: (event: CalendarEvent) => void;
    resetForm: () => void;
    handleEventSave: (calendarData: any) => Promise<void>;
    handleEventDelete: (calendarData: any) => Promise<void>;
    handleRecurringDeleteThis: (calendarData: any) => Promise<void>;
    handleRecurringDeleteAll: (calendarData: any) => Promise<void>;
}
export declare function useEventForm({ calendars, localSettings, onEventSaved, onClose, }: UseEventFormProps): UseEventFormReturn;
export {};
//# sourceMappingURL=use-event-form.d.ts.map