[build]
builder = "NIXPACKS"
watchPatterns = ["apps/notifications/**", "go.mod", "go.sum"]

[deploy]
startCommand = "go mod tidy && go run main.go"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
