export declare const EventHeight = 24;
export declare const EventGap = 4;
export declare const WeekCellsHeight = 72;
export declare const AgendaDaysToShow = 30;
export declare const StartHour = 0;
export declare const EndHour = 23;
export declare const DefaultStartHour = 9;
export declare const DefaultEndHour = 10;
//# sourceMappingURL=constants.d.ts.map