export declare const LOADING_MESSAGES: {
    readonly AUTH: readonly ["Authenticating...", "Signing you in...", "Verifying credentials...", "Securing your session...", "Connecting to your account..."];
    readonly GENERAL: readonly ["Loading...", "Getting things ready...", "Preparing your calendar...", "Setting up your workspace...", "Just a moment...", "Loading your data...", "Preparing your view...", "Almost ready...", "Syncing your information...", "Organizing your schedule..."];
    readonly CALENDAR: readonly ["Loading calendar...", "Syncing events...", "Updating your schedule...", "Fetching calendar data...", "Organizing your events...", "Loading your appointments...", "Refreshing calendar view...", "Syncing with calendars...", "Updating event details...", "Loading calendar settings..."];
    readonly SETTINGS: readonly ["Loading settings...", "Configuring preferences...", "Updating your preferences...", "Loading configuration...", "Preparing settings...", "Syncing preferences...", "Customizing your experience...", "Loading user preferences...", "Configuring your workspace...", "Setting up your account..."];
    readonly SYNC: readonly ["Syncing data...", "Updating information...", "Refreshing content...", "Syncing changes...", "Updating your calendar...", "Synchronizing events...", "Refreshing your data...", "Syncing with server...", "Updating local cache...", "Fetching latest changes..."];
    readonly STARTUP: readonly ["Starting Rocal...", "Initializing application...", "Loading your workspace...", "Preparing your calendar app...", "Setting up Rocal...", "Launching your calendar...", "Getting your calendar ready...", "Booting up your schedule...", "Initializing your workspace...", "Welcome to Rocal..."];
    readonly ENGAGING: readonly ["Organizing your time...", "Crafting your perfect schedule...", "Polishing your calendar...", "Brewing your daily plan...", "Assembling your agenda...", "Fine-tuning your schedule...", "Optimizing your time...", "Curating your calendar...", "Building your day...", "Scheduling success..."];
};
export declare const COMBINED_MESSAGES: {
    readonly PAGE_LOAD: readonly ["Starting Rocal...", "Initializing application...", "Loading your workspace...", "Preparing your calendar app...", "Setting up Rocal...", "Launching your calendar...", "Getting your calendar ready...", "Booting up your schedule...", "Initializing your workspace...", "Welcome to Rocal...", "Loading...", "Getting things ready...", "Preparing your calendar...", "Setting up your workspace...", "Just a moment...", "Loading your data...", "Preparing your view...", "Almost ready...", "Syncing your information...", "Organizing your schedule..."];
    readonly AUTH_FLOW: readonly ["Authenticating...", "Signing you in...", "Verifying credentials...", "Securing your session...", "Connecting to your account...", "Loading...", "Getting things ready...", "Preparing your calendar...", "Setting up your workspace...", "Just a moment...", "Loading your data...", "Preparing your view...", "Almost ready...", "Syncing your information...", "Organizing your schedule..."];
    readonly CALENDAR_LOAD: readonly ["Loading calendar...", "Syncing events...", "Updating your schedule...", "Fetching calendar data...", "Organizing your events...", "Loading your appointments...", "Refreshing calendar view...", "Syncing with calendars...", "Updating event details...", "Loading calendar settings...", "Syncing data...", "Updating information...", "Refreshing content...", "Syncing changes...", "Updating your calendar...", "Synchronizing events...", "Refreshing your data...", "Syncing with server...", "Updating local cache...", "Fetching latest changes..."];
    readonly SETTINGS_LOAD: readonly ["Loading settings...", "Configuring preferences...", "Updating your preferences...", "Loading configuration...", "Preparing settings...", "Syncing preferences...", "Customizing your experience...", "Loading user preferences...", "Configuring your workspace...", "Setting up your account...", "Loading...", "Getting things ready...", "Preparing your calendar...", "Setting up your workspace...", "Just a moment...", "Loading your data...", "Preparing your view...", "Almost ready...", "Syncing your information...", "Organizing your schedule..."];
    readonly DATA_SYNC: readonly ["Syncing data...", "Updating information...", "Refreshing content...", "Syncing changes...", "Updating your calendar...", "Synchronizing events...", "Refreshing your data...", "Syncing with server...", "Updating local cache...", "Fetching latest changes...", "Loading calendar...", "Syncing events...", "Updating your schedule...", "Fetching calendar data...", "Organizing your events...", "Loading your appointments...", "Refreshing calendar view...", "Syncing with calendars...", "Updating event details...", "Loading calendar settings..."];
    readonly ENGAGING_MIX: readonly ["Organizing your time...", "Crafting your perfect schedule...", "Polishing your calendar...", "Brewing your daily plan...", "Assembling your agenda...", "Fine-tuning your schedule...", "Optimizing your time...", "Curating your calendar...", "Building your day...", "Scheduling success...", ...("Loading..." | "Getting things ready..." | "Preparing your calendar..." | "Setting up your workspace..." | "Just a moment..." | "Loading your data..." | "Preparing your view..." | "Almost ready..." | "Syncing your information..." | "Organizing your schedule..." | "Loading calendar..." | "Syncing events..." | "Updating your schedule..." | "Fetching calendar data..." | "Organizing your events..." | "Loading your appointments..." | "Refreshing calendar view..." | "Syncing with calendars..." | "Updating event details..." | "Loading calendar settings...")[]];
};
export declare function getRandomMessage(messages: readonly string[]): string;
export declare function getLoadingMessage(context: keyof typeof COMBINED_MESSAGES): string;
export declare const MESSAGE_CYCLE_CONFIG: {
    readonly CYCLE_INTERVAL: 2000;
    readonly INITIAL_DELAY: 1000;
    readonly TRANSITION_DURATION: 300;
};
//# sourceMappingURL=loading-messages.d.ts.map