import type { Color } from "./color-utils";
import { Size } from "./types";

export type IconColor = Color | "source";

export enum Icon {
  At = "at",
  Archive = "archive",
  ArrowDown = "arrow-down",
  ArrowLeft = "arrow-left",
  ArrowRight = "arrow-right",
  ArrowUp = "arrow-up",
  Bell = "bell",
  BellSlash = "bell-slash",
  Bold = "bold",
  Calendar = "calendar",
  Check = "check",
  CheckCircle = "check-circle",
  CheckboxEmpty = "checkbox-empty",
  CheckboxFilled = "checkbox-filled",
  ChevronDown = "chevron-down",
  ChevronLeft = "chevron-left",
  ChevronRight = "chevron-right",
  ChevronUp = "chevron-up",
  Clipboard = "clipboard",
  Clock = "clock",
  ClockSlash = "clock-slash",
  Close = "close",
  Cloud = "cloud",
  Compose = "compose",
  Copy = "copy",
  Download = "download",
  Dot = "dot",
  Edit = "edit",
  Envelope = "envelope",
  EnvelopeFilled = "envelope-filled",
  EnvelopeRead = "envelope-read",
  EnvelopeUnread = "envelope-unread",
  Expand = "expand",
  ExternalLink = "external-link",
  Eye = "eye",
  EyeSlash = "eye-slash",
  File = "file",
  FilePlus = "file-plus",
  Filter = "filter",
  Flag = "flag",
  Folder = "folder",
  FolderArrow = "folder-arrow",
  Forward = "forward",
  ForwardEmail = "forward-email",
  Globe = "globe",
  Heart = "heart",
  Home = "home",
  Image = "image",
  Inbox = "inbox",
  Info = "info",
  Italic = "italic",
  Link = "link",
  Lock = "lock",
  Mailbox = "mailbox",
  Menu = "menu",
  Minus = "minus",
  Moon = "moon",
  MoveMailbox = "move-mailbox",
  OverflowH = "overflow-h",
  OverflowV = "overflow-v",
  PaperClip = "paper-clip",
  Pause = "pause",
  Play = "play",
  Plus = "plus",
  PlusCircle = "plus-circle",
  PopOut = "pop-out",
  Printer = "printer",
  QuestionCircle = "question-circle",
  Redo = "redo",
  Reload = "reload",
  Reply = "reply",
  ReplyAll = "reply-all",
  Search = "search",
  Send = "send",
  Settings = "settings",
  ShieldCheck = "shield-check",
  Smile = "smile",
  Spam = "spam",
  Star = "star",
  Sun = "sun",
  Tag = "tag",
  Trash = "trash",
  Underline = "underline",
  Undo = "undo",
  Unlock = "unlock",
  Upload = "upload",
  User = "user",
  UserPlus = "user-plus",
  Warning = "warning",
  XCircle = "x-circle",
  ZoomMinus = "zoom-minus",
  ZoomPlus = "zoom-plus",
}

export const ICON_SIZE: Record<Size, number> = {
  xlarge: 48,
  large: 36,
  xmedium: 24,
  medium: 16,
  small: 14,
  xsmall: 12,
};
